config/routes.rb
Rails.application.routes.draw do
  constraints Clearance::Constraints::SignedIn.new do
    root to: "dashboards#show"
  end

  root to: "homes#show"
  resources :classrooms
  resources :students
  resources :challenges, only: [:edit, :update, :delete]
  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]

  resources :users, only: [:create] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end

  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"
  get 'hello_world', to: 'hello_world#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/challenge.rb
class Challenge < ApplicationRecord
  belongs_to :student

  validates :type, presence: true
  validates :date, presence: true

  has_many :correct_answers
  has_many :incorrect_answers

  def all_lowercase_letters
    @lowercase = ["a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k", "l", "m", "n", "o", "p","q", "r", "s", "t", "u", "v", "w", "x", "y", "z"]
  end

  def all_capital_letters
    @capital = ["A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M", "N", "O", "P", "Q", "R", "S", "T", "U", "V", "W", "X", "Y", "Z"]
  end
  
  
end

app/models/classroom.rb
class Classroom < ApplicationRecord
  belongs_to :user
end

app/models/correct_answer.rb
class CorrectAnswer < ApplicationRecord
  belongs_to :challenge

  validates :letter, presence: true
  validates :challenge, presence: true
  
end

app/models/incorrect_answer.rb
class IncorrectAnswer < ApplicationRecord
  belongs_to :challenge

  validates :letter, presence: true
  validates :challenge, presence: true 
end

app/models/student.rb
class Student < ApplicationRecord
  belongs_to :classroom
  has_many :challenges
  has_many :correct_answers, through: :challenges

  validates :name, presence: true, length: { in: 1...140 }
  validates :user, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  include Clearance::User

  validates :name, presence: true
  validates :email, presence: true, uniqueness: true

  has_many :classrooms, dependent: :destroy
  has_many :students, through: :classrooms 

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Clearance::Controller
  protect_from_forgery with: :exception
end

app/controllers/challenges_controller.rb
class ChallengesController < ApplicationController

   
end

app/controllers/classrooms_controller.rb
class ClassroomsController < ApplicationController
    def create
      classroom = current_user.classrooms.create(classroom_params)
      redirect_to root_path, redirect_options_for(classroom)
    end
    
    private
  
    def classroom_params
      params.require(:user).permit(:name)
    end

    def redirect_options_for(classroom)
      if classroom.persisted?
        { notice: "Classroom successfully created" }
      else
        { alert: "Classroom not created. Name must be 2 to 140 characters" }
      end
    end
   
  end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  def show
    render
  end
end

app/controllers/hello_world_controller.rb
# frozen_string_literal: true

class HelloWorldController < ApplicationController
  layout "hello_world"

  def index
    @hello_world_props = { name: "Stranger" }
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def show
    render
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
    def create
      classroom = Classroom.find_by(classroom_params)
      student = classroom.students.create(student_params)
      redirect_to root_path, redirect_options_for(student)
    end
    
    private
  
    def student_params
      params.require(:user).permit(:name)
    end

    def redirect_options_for(student)
      if student.persisted?
        { notice: "Student successfully created" }
      else
        { alert: "Student not created. Name must be 2 to 140 characters" }
      end
    end
   
  end

app/controllers/users_controller.rb
class UsersController < Clearance::UsersController
  private

  def user_params
    params.require(:user).permit(:name, :email, :password)
  end
 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/dashboards/show.html.erb
<h1>Dashboard<h1>

app/views/hello_world/index.html.erb
<h1>Hello World</h1>
<%= react_component("HelloWorld", props: @hello_world_props, prerender: false) %>

app/views/homes/show.html.erb
<h1>Home</h1>
<%= react_component("HelloWorld", props: @hello_world_props, prerender: false) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlphabetAware</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

     <!--  NOTE: Must use defer and not async to keep async scripts loading in correct order  -->
    <%= javascript_pack_tag('vendor-bundle', 'data-turbolinks-track': true, defer: true) %>
    <%= javascript_pack_tag('app-bundle', 'data-turbolinks-track': true, defer: true) %>
  
  </head>

  <body>
     <% if signed_in? %>
      Signed in as: <%= current_user.email %>
      <%= button_to 'Sign out', sign_out_path, method: :delete %>
    <% else %>
      <%= link_to 'Sign in', sign_in_path %>
    <% end %>

    <div id="flash">
      <% flash.each do |key, value| %>
        <div class="flash <%= key %>"><%= value %></div>
      <% end %>
    </div>

    <%= yield %>
    
  </body>
</html>

app/views/layouts/hello_world.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ReactOnRailsWithWebpacker</title>
    <%= csrf_meta_tags %>
    <%= javascript_pack_tag 'hello-world-bundle' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/_form.html.erb
<div class="text-field">
  <%= form.label :name %>
  <%= form.text_field :name %>
</div>

<div class="text-field">
  <%= form.label :email %>
  <%= form.email_field :email, type: 'email' %>
</div>

<div class="password-field">
  <%= form.label :password %>
  <%= form.password_field :password %>
</div>

app/views/users/new.html.erb
<div id="clearance" class="sign-up">
  <h2><%= t(".title") %></h2>

  <%= form_for @user do |form| %>
    <%= render partial: '/users/form', object: form %>

    <div class="submit-field">
      <%= form.submit %>
    </div>

    <div class="other-links">
      <%= link_to t(".sign_in"), sign_in_path %>
    </div>
  <% end %>
</div>